services:
  action:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "5055:5055"
    extra_hosts:
      - "host.docker.internal:host-gateway"
